Repository Team-Tokkit/Tokkit-Server-Admin, pull requests merged in 2025-05, with the labels that each got.

#4 Feat/#3 [Admin] 공지사항 관리 기능 추가
  src/main/java/dev/admin/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/dev/admin/notice/controller/NoticeController.java
  src/main/java/dev/admin/notice/dto/request/NoticeRequestDto.java
  src/main/java/dev/admin/notice/dto/response/NoticeResponseDto.java
  src/main/java/dev/admin/notice/repository/NoticeRepository.java
  src/main/java/dev/admin/notice/service/command/NoticeCommandService.java
  src/main/java/dev/admin/notice/service/command/NoticeCommandServiceImpl.java
  src/main/java/dev/admin/notice/service/query/NoticeQueryService.java
  src/main/java/dev/admin/notice/service/query/NoticeQueryServiceImpl.java
Labels: FEAT

#6 Feat/#5 [Admin] ApiRequestLog 차트,페이지,상세 기능 구현
  .github/workflows/deploy.yml
  src/main/java/dev/admin/api_request_log/controller/ApiRequestLogController.java
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogChartResponseDto.java
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogDetailResponseDto.java
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogPageItemDto.java
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogPageResponseDto.java
  src/main/java/dev/admin/api_request_log/dto/response/PageableInfo.java
  src/main/java/dev/admin/api_request_log/entity/ApiRequestLog.java
  src/main/java/dev/admin/api_request_log/repository/ApiRequestLogRepository.java
  src/main/java/dev/admin/api_request_log/service/query/ApiRequestLogQueryService.java
  src/main/java/dev/admin/api_request_log/service/query/ApiRequestLogQueryServiceImpl.java
  src/main/java/dev/admin/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/dev/admin/global/util/DateTimeUtil.java
  src/main/java/dev/admin/login_log/entity/LoginLog.java
  src/main/java/dev/admin/login_log/enums/Event.java
  src/main/java/dev/admin/login_log/repository/LoginLogRepository.java
  src/main/java/dev/admin/system_error_log/entity/SystemErrorLog.java
  src/main/java/dev/admin/system_error_log/enums/Severity.java
  src/main/java/dev/admin/transaction/entity/Transaction.java
  src/main/java/dev/admin/transaction/enums/TransactionStatus.java
  src/main/java/dev/admin/transaction/enums/TransactionType.java
  src/main/java/dev/admin/transaction/repository/TransactionRepository.java
  src/main/java/dev/admin/user_login_log/repository/UserLoginLogRepository.java
  src/main/java/dev/admin/wallet/entity/Wallet.java
  src/test/java/dev/admin/api_request_log/service/query/ApiRequestLogQueryServiceImplTest.java
Labels: FEAT

#8 ✨ Feat/#7 User,Merchant 관리자 기능 추가 (조회,수정,상태변경)
  build.gradle
  src/main/java/dev/admin/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/dev/admin/global/config/SecurityConfig.java
  src/main/java/dev/admin/global/util/PasswordUtil.java
  src/main/java/dev/admin/merchant/controller/MerchantController.java
  src/main/java/dev/admin/merchant/dto/request/UpdateMerchantRequestDto.java
  src/main/java/dev/admin/merchant/dto/request/UpdateMerchantStatusRequestDto.java
  src/main/java/dev/admin/merchant/dto/response/MerchantDetailResponseDto.java
  src/main/java/dev/admin/merchant/dto/response/MerchantSimpleResponseDto.java
  src/main/java/dev/admin/merchant/entity/Merchant.java
  src/main/java/dev/admin/merchant/repository/MerchantRepository.java
  src/main/java/dev/admin/merchant/service/command/MerchantCommandService.java
  src/main/java/dev/admin/merchant/service/command/MerchantCommandServiceImpl.java
  src/main/java/dev/admin/merchant/service/query/MerchantQueryService.java
  src/main/java/dev/admin/merchant/service/query/MerchantQueryServiceImpl.java
  src/main/java/dev/admin/user/controller/UserController.java
  src/main/java/dev/admin/user/dto/request/UpdateUserRequestDto.java
  src/main/java/dev/admin/user/dto/request/UpdateUserStatusRequestDto.java
  src/main/java/dev/admin/user/dto/response/UserDetailResponseDto.java
  src/main/java/dev/admin/user/dto/response/UserSimpleResponseDto.java
  src/main/java/dev/admin/user/entity/User.java
  src/main/java/dev/admin/user/repository/UserRepository.java
  src/main/java/dev/admin/user/service/command/UserCommandService.java
  src/main/java/dev/admin/user/service/command/UserCommandServiceImpl.java
  src/main/java/dev/admin/user/service/query/UserQueryService.java
  src/main/java/dev/admin/user/service/query/UserQueryServiceImpl.java
  src/test/java/dev/admin/merchant/service/command/MerchantCommandServiceImplTest.java
  src/test/java/dev/admin/merchant/service/query/MerchantQueryServiceImplTest.java
  src/test/java/dev/admin/user/service/command/UserCommandServiceImplTest.java
  src/test/java/dev/admin/user/service/query/UserQueryServiceImplTest.java
Labels: FEAT

#10 ♻️ Refactor/#9 api request log status
  src/main/java/dev/admin/api_request_log/repository/ApiRequestLogRepository.java
  src/main/java/dev/admin/api_request_log/service/query/ApiRequestLogQueryServiceImpl.java
  src/main/java/dev/admin/global/config/SwaggerConfig.java
Labels: REFACTOR

#13 :sparkles: feat: 시스템 로그, 로그인 로그 , 유저, 가맹점주 관리 시스템 구현
  src/main/java/dev/admin/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/dev/admin/global/controller/S3Controller.java
  src/main/java/dev/admin/login_log/controller/LoginLogController.java
  src/main/java/dev/admin/login_log/dto/request/LoginLogSearchDto.java
  src/main/java/dev/admin/login_log/dto/response/LoginLogResponseDto.java
  src/main/java/dev/admin/login_log/dto/response/LoginLogSimpleResponseDto.java
  src/main/java/dev/admin/login_log/repository/LoginLogRepository.java
  src/main/java/dev/admin/login_log/service/query/LoginLogQueryService.java
  src/main/java/dev/admin/login_log/service/query/LoginLogQueryServiceImpl.java
  src/main/java/dev/admin/merchant/dto/request/UpdateMerchantRequestDto.java
  src/main/java/dev/admin/merchant/entity/Merchant.java
  src/main/java/dev/admin/merchant/service/command/MerchantCommandServiceImpl.java
  src/main/java/dev/admin/merchant/service/query/MerchantQueryServiceImpl.java
  src/main/java/dev/admin/store/enums/StoreCategory.java
  src/main/java/dev/admin/store/repository/StoreRepository.java
  src/main/java/dev/admin/store/service/command/StoreCommandService.java
  src/main/java/dev/admin/store/service/command/StoreCommandServiceImpl.java
  src/main/java/dev/admin/system_error_log/controller/SystemErrorLogController.java
  src/main/java/dev/admin/system_error_log/dto/request/SystemErrorLogSearchDto.java
  src/main/java/dev/admin/system_error_log/dto/response/SystemErrorLogResponseDto.java
  src/main/java/dev/admin/system_error_log/dto/response/SystemErrorLogSimpleResponseDto.java
  src/main/java/dev/admin/system_error_log/entity/SystemErrorLog.java
  src/main/java/dev/admin/system_error_log/repository/SystemErrorLogRepository.java
  src/main/java/dev/admin/system_error_log/service/query/SystemErrorLogQueryService.java
  src/main/java/dev/admin/system_error_log/service/query/SystemErrorLogQueryServiceImpl.java
  src/main/java/dev/admin/transaction/controller/TransactionController.java
  src/main/java/dev/admin/transaction/dto/request/TransactionSearchDto.java
  src/main/java/dev/admin/transaction/dto/response/TransactionResponseDto.java
  src/main/java/dev/admin/transaction/dto/response/TransactionSimpleResponseDto.java
  src/main/java/dev/admin/transaction/repository/TransactionRepository.java
  src/main/java/dev/admin/transaction/service/query/TransactionQueryService.java
  src/main/java/dev/admin/transaction/service/query/TransactionQueryServiceImpl.java
  src/main/java/dev/admin/user/service/command/UserCommandServiceImpl.java
  src/main/java/dev/admin/voucher/dto/request/CreateVoucherRequestDto.java
  src/main/java/dev/admin/voucher/dto/request/UpdateVoucherRequestDto.java
  src/main/java/dev/admin/voucher/dto/request/VoucherSearchDto.java
  src/main/java/dev/admin/voucher/dto/response/VoucherResponseDto.java
  src/main/java/dev/admin/voucher/dto/response/VoucherSimpleResponseDto.java
  src/main/java/dev/admin/voucher/service/command/VoucherCommandService.java
  src/main/java/dev/admin/voucher/service/command/VoucherCommandServiceImpl.java
  src/main/java/dev/admin/voucher/service/query/VoucherQueryService.java
  src/main/java/dev/admin/voucher/service/query/VoucherQueryServiceImpl.java
  src/test/java/dev/admin/login_log/service/query/LoginLogQueryServiceImplTest.java
  src/test/java/dev/admin/system_error_log/service/query/SystemErrorLogQueryServiceImplTest.java
  src/test/java/dev/admin/transaction/service/query/TransactionQueryServiceImpl.java
Labels: FEAT

#14 :sparkles:Feat/#11 system log
  src/main/java/dev/admin/login_log/controller/LoginLogController.java
Labels: FEAT

#16 :recycle: refactor: IP,MerchantID 추가
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogDetailResponseDto.java
  src/main/java/dev/admin/api_request_log/dto/response/ApiRequestLogPageItemDto.java
  src/main/java/dev/admin/api_request_log/entity/ApiRequestLog.java
  src/main/java/dev/admin/api_request_log/repository/ApiRequestLogRepository.java
  src/main/java/dev/admin/api_request_log/service/query/ApiRequestLogQueryServiceImpl.java
  src/main/java/dev/admin/login_log/dto/response/LoginLogSimpleResponseDto.java
  src/main/java/dev/admin/system_error_log/dto/response/SystemErrorLogResponseDto.java
  src/main/java/dev/admin/system_error_log/entity/SystemErrorLog.java
Labels: REFACTOR

#17 Feat: 바우처 관련 api 구현
  src/main/application.yml
  src/main/java/dev/admin/TokkitServerAdminApplication.java
  src/main/java/dev/admin/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/dev/admin/global/controller/S3Controller.java
  src/main/java/dev/admin/global/repository/VoucherImageRepository.java
  src/main/java/dev/admin/global/repository/VoucherStoreRepository.java
  src/main/java/dev/admin/global/service/S3Service.java
  src/main/java/dev/admin/region/repository/RegionRepository.java
  src/main/java/dev/admin/store/controller/StoreController.java
  src/main/java/dev/admin/store/dto/request/StoreSearchRequestDto.java
  src/main/java/dev/admin/store/dto/response/StoreListResponseDto.java
  src/main/java/dev/admin/store/entity/Store.java
  src/main/java/dev/admin/store/repository/StoreCustomRepository.java
  src/main/java/dev/admin/store/repository/StoreCustomRepositoryImpl.java
  src/main/java/dev/admin/store/repository/StoreRepository.java
  src/main/java/dev/admin/store/service/query/StoreQueryService.java
  src/main/java/dev/admin/store/service/query/StoreQueryServiceImpl.java
  src/main/java/dev/admin/voucher/controller/VoucherController.java
  src/main/java/dev/admin/voucher/dto/request/CreateVoucherRequestDto.java
  src/main/java/dev/admin/voucher/dto/request/UpdateVoucherRequestDto.java
  src/main/java/dev/admin/voucher/dto/request/VoucherSearchRequest.java
  src/main/java/dev/admin/voucher/dto/response/VoucherResponseDto.java
  src/main/java/dev/admin/voucher/dto/response/VoucherSimpleResponseDto.java
  src/main/java/dev/admin/voucher/entity/Voucher.java
  src/main/java/dev/admin/voucher/repository/VoucherCustomRepository.java
  src/main/java/dev/admin/voucher/repository/VoucherCustomRepositoryImpl.java
  src/main/java/dev/admin/voucher/repository/VoucherRepository.java
  src/main/java/dev/admin/voucher/service/command/VoucherCommandService.java
  src/main/java/dev/admin/voucher/service/command/VoucherCommandServiceImpl.java
  src/main/java/dev/admin/voucher/service/query/VoucherQueryService.java
  src/main/java/dev/admin/voucher/service/query/VoucherQueryServiceImpl.java
Labels: FEAT

#19 ♻️ Refactor#18: 로그인, 에러, 트랜잭션 최신순 정렬 추가
  src/main/java/dev/admin/login_log/repository/LoginLogRepository.java
  src/main/java/dev/admin/system_error_log/repository/SystemErrorLogRepository.java
  src/main/java/dev/admin/transaction/repository/TransactionRepository.java
Labels: REFACTOR

#23 ♻️ Refactor: User Dto 필드명 통일
  src/main/application.yml
  src/main/java/dev/admin/user/dto/request/UpdateUserRequestDto.java
  src/main/java/dev/admin/user/dto/response/UserDetailResponseDto.java
  src/main/java/dev/admin/user/service/command/UserCommandServiceImpl.java
Labels: REFACTOR

#37 ✨ Feat: CI/CD (CodeDeploy) #36
  .github/workflows/deploy_prod.yml
  Dockerfile
  src/main/java/dev/admin/global/controller/HealthCheckController.java
Labels: FEAT

#40 :recycle: Refactor: Update CorsFilter
  src/main/java/dev/admin/global/config/CorsConfig.java
Labels: SECURITY

#42 :sparkles: Feat: Add Unified Log Service
  src/main/java/dev/admin/unified_logs/controller/UnifiedLogController.java
  src/main/java/dev/admin/unified_logs/dto/request/UnifiedLogFilterRequest.java
  src/main/java/dev/admin/unified_logs/dto/response/UnifiedLogResponseDto.java
  src/main/java/dev/admin/unified_logs/service/query/UnifiedLogQueryService.java
  src/main/java/dev/admin/unified_logs/service/query/UnifiedLogQueryServiceImpl.java
Labels: FEAT

#47 :recycle: Refactor: Cors Filter 수정
  src/main/java/dev/admin/global/config/CorsConfig.java
Labels: REFACTOR
